services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: web-bff-mqtt
    restart: unless-stopped
    network_mode: host

  my-app:
    build: .
    container_name: web-bff
    restart: unless-stopped
    network_mode: host
