name: Specmatic Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: "10 0 * * *" # Runs daily at 10 past midnight
  workflow_dispatch:

jobs:
  send-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Initialize Specmatic License and Download Specmatic Enterprise
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ~/.specmatic
          echo "${{ secrets.SPECMATIC_LICENSE_KEY }}" > ~/.specmatic/specmatic-license.txt
          curl -fsSL https://docs.specmatic.io/install-specmatic-enterprise.sh | bash

      - name: Run tests and send report
        if: github.ref == 'refs/heads/main'
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
            GENERATIVE_TESTS=true ./ci.sh . || true
          else
            ./ci.sh . || true
          fi
          java -jar ~/.specmatic/specmatic-enterprise.jar send-report \
            --repo-id="${{ github.event.repository.id }}" \
            --repo-name="${{ github.event.repository.name }}" \
            --repo-url="${{ github.server_url }}/${{ github.repository }}" \
            --branch-name="${{ github.ref_name }}"
